name: Deploy Civitas to Lenovo Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 1. Nieuwste code ophalen van GitHub
        uses: actions/checkout@v4

      - name: 2. Civitas bouwen met Maven
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: 3. De applicatie pauzeren via systemd
        run: sudo systemctl stop civitas

      - name: 4. De nieuwe .jar overzetten naar de home-folder
        run: cp target/CivitasWebApp-0.0.1-SNAPSHOT.jar /home/dogukan/

      - name: 5. De applicatie weer starten via systemd
        run: sudo systemctl start civitas